version: "2"
services:
  node:
    build: 
      context: ./app
      dockerfile: Dockerfile-dev # change this to Dockerfile-dev; it'll use nodemon
    volumes:
      - ./app:/app
    links:
      - postgres
    depends_on:
      - "postgres"
    environment:
      POSTGRES_URL: "postgres://postgres@postgres/postgres"
      WORKER_COUNT: 1
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "80:31415"
    depends_on:
      - node
    links:
      - node
    restart: always
  postgres:
    image: postgres:alpine
    restart: always
